### ISSUE TITLE
java.lang.NoSuchMethodError: com/sun/glass/ui/Screen.<init>

### ISSUE THREAD

**Issue by utybo** [openjfx/javafx-gradle-plugin#42]
I keep getting this error in multiple circumstances, including `gradle run`, and I can't do much about it.

```
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: com/sun/glass/ui/Screen.<init>(JIIIIIIIIIIIFF)V (loaded from file:/C:/Users/matth/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-graphics/12.0.1/18a01ffdd4edb82e7da3bc99937c6a608d1eaaa6/javafx-graphics-12.0.1-win.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@b3361661) called from class com.sun.glass.ui.win.WinApplication (loaded from file:/C:/Users/matth/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-graphics/12.0.1/18a01ffdd4edb82e7da3bc99937c6a608d1eaaa6/javafx-graphics-12.0.1-win.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@b3361661).
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
	at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Screen.java:412)
	at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:152)
	at com.sun.glass.ui.Application$$Lambda$120.00000000A0FAC830.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at com.sun.glass.ui.win.WinApplication$$Lambda$124.00000000A0EE9880.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:825)
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: com/sun/glass/ui/Screen.<init>(JIIIIIIIIIIIFF)V (loaded from file:/C:/Users/matth/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-graphics/12.0.1/18a01ffdd4edb82e7da3bc99937c6a608d1eaaa6/javafx-graphics-12.0.1-win.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@b3361661) called from class com.sun.glass.ui.win.WinApplication (loaded from file:/C:/Users/matth/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-graphics/12.0.1/18a01ffdd4edb82e7da3bc99937c6a608d1eaaa6/javafx-graphics-12.0.1-win.jar by jdk.internal.loader.ClassLoaders$AppClassLoader@b3361661).
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
	at javafx.graphics/com.sun.glass.ui.Screen.initScreens(Screen.java:412)
	at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:152)
	at com.sun.glass.ui.Application$$Lambda$120.00000000A0FAC830.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at com.sun.glass.ui.win.WinApplication$$Lambda$124.00000000A0EE9880.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:825)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at javafx.graphics/com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(D3DPipeline.java:205)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(QuantumToolkit.java:738)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(QuantumToolkit.java:334)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(QuantumToolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit$$Lambda$117.00000000A1A1F210.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.Application.lambda$run$1(Application.java:153)
	at com.sun.glass.ui.Application$$Lambda$120.00000000A0FAC830.run(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at com.sun.glass.ui.win.WinApplication$$Lambda$124.00000000A0EE9880.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:825)

```

**Comment by utybo** [comment]
Apologies, this was an issue on my end. A note for people who intend to use AdoptOpenJDK, the OpenJ9 VM does not seem to include the `glass.dll` library which is required for JavaFX
